Encourage/Silicus.EncourageWithAzureAd.Web/Models/NominationViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace Silicus.EncourageWithAzureAd.Web.Models
{
    public class NominationViewModel
    {
        [Required(ErrorMessage = "Select Nomination Category")]
        public int AwardId { get; set; }
        public int NominationId { get; set; }
        public int ManagerId { get; set; }
        [Required(ErrorMessage = "Select Employee")]
        public int ResourceId { get; set; }
        [Required(ErrorMessage = "Select Project")]
        public int? ProjectID { get; set; }
        [Required(ErrorMessage = "Select Department")]
        public int? DepartmentId { get; set; }
        [Required(ErrorMessage = "Please mention the reason")]
        [MaxLength(500, ErrorMessage = "Reason should not exceed 500 letters.")]
        public string OtherNominationReason { get; set; }
        public bool IsOther { get; set; }
        public bool IsLocked { get; set; }
        public bool? IsSubmitted { get; set; }
        public bool IsHistorical { get; set; }
        [Required(ErrorMessage = "Please provide Comment")]
        public string MainComment { get; set; }
        [Required(ErrorMessage = "Select Project or Department")]
        public string SelectResourcesBy { get; set; }  //from project or from department
        [Required(ErrorMessage = "Please provide comment against criteria")]
        public IList<CriteriaCommentViewModel> Comments { get; set; }
        public SelectList ListOfAwards { get; set; }
        public SelectList ProjectsUnderCurrentUser { get; set; }
        public SelectList DepartmentsUnderCurrentUser { get; set; }
        public SelectList Resources { get; set; }
        public DateTime CustomDate { get; set; }

        public DateTime SomCustomDate { get; set; }
        public DateTime PinnacleCustomDate { get; set; }

        #region For Displaying on Edit Nomination
        public string ResourceName { get; set; }
        public string AwardName { get; set; }
        public string ProjectOrDeptName { get; set; }
        #endregion For Displaying on Edit Nomination


        public NominationViewModel()
        {
            Comments = new List<CriteriaCommentViewModel>();
        }

    }
}

Encourage/Silicus.EncourageWithAzureAd.Web/Controllers/NominationController.cs
using Silicus.Encourage.DAL.Interfaces;
using Silicus.Encourage.Models;
using Silicus.Encourage.Services.Interface;
using Silicus.Encourage.Web.Filters;
using Silicus.EncourageWithAzureAd.Web.Enums;
using Silicus.EncourageWithAzureAd.Web.Models;
using Silicus.FrameWorx.Logger;
using Silicus.UtilityContainer.Entities;
using Silicus.UtilityContainer.Models.DataObjects;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Globalization;
using System.Linq;
using System.Web.Mvc;

namespace Silicus.EncourageWithAzureAd.Web.Controllers
{
    [Authorize]
    public class NominationController : Controller
    {
        private readonly IAwardService _awardService;
        private readonly IReviewService _reviewService;
        private readonly INominationService _nominationService;
        private readonly ICommonDataBaseContext _commonDbContext;
        private readonly IEncourageDatabaseContext _encourageDatabaseContext;
        private readonly TextInfo _textInfo;
        private readonly ILogger _logger;
        private readonly ICustomDateService _customDateService;

        public NominationController(INominationService nominationService, Encourage.DAL.Interfaces.IDataContextFactory dataContextFactory,
            ICommonDbService commonDbService, IAwardService awardService, IReviewService reviewService, ILogger logger, ICustomDateService customDateService)
        {
            _nominationService = nominationService;
            _commonDbContext = commonDbService.GetCommonDataBaseContext();
            _encourageDatabaseContext = dataContextFactory.CreateEncourageDbContext();
            _awardService = awardService;
            _reviewService = reviewService;
            _textInfo = new CultureInfo("en-US", false).TextInfo;
            _logger = logger;
            _customDateService = customDateService;
        }

        #region Nomination
        [HttpGet]
        public ActionResult GetLockedAwardCategories()
        {
            return Json(_nominationService.GetNominationLockStatus(), JsonRequestBehavior.AllowGet);
        }

        // GET: Nomination/Create
        [HttpGet]
        [CustomeAuthorize(AllowedRole = "Manager")]
        public ActionResult AddNomination()
        {
            _logger.Log("Nomination-AddNomination-GET");

            var model = new NominationViewModel();
            var userEmailAddress = User.Identity.Name;
            var projects = _awardService.GetProjectsUnderCurrentUserAsManager(userEmailAddress);
            var listOfAwards = _awardService.GetAllAwards();

            if (projects.Any())
            {
                model.ProjectsUnderCurrentUser = new SelectList(projects, "Id", "Name");
            }

            var depts = _awardService.GetDepartmentsUnderCurrentUserAsManager(userEmailAddress);
            if (depts.Count > 0)
            {
                model.DepartmentsUnderCurrentUser = new SelectList(depts, "Id", "Name");
            }

            foreach (var award in listOfAwards)
            {
                switch (award.Code)
                {
                    default:
                    case "SOM":
                        model.SomCustomDate = _customDateService.GetCustomDate(award.Id);
                        break;
                    case "PINNACLE":
                        model.PinnacleCustomDate = _customDateService.GetCustomDate(award.Id);
                        break;
                }
            }

            model.Resources = new SelectList(new List<User>(), "Id", "DisplayName");
            model.ListOfAwards = new SelectList(listOfAwards, "Id", "Name");
            model.ManagerId = _awardService.GetUserIdFromEmail(userEmailAddress);

            return View(model);
        }

        [HttpPost]
        [CustomeAuthorize(AllowedRole = "Manager")]
        public ActionResult AddNomination(NominationViewModel model, string submit)
        {
            _logger.Log("Nomination-AddNomination-POST");
            try
            {
                _logger.Log("Nomination-AddNomination-POST-try");
                var customDate = _customDateService.GetCustomDate(model.AwardId);
                var awardOfCurrentNomination = _awardService.GetAwardById(model.AwardId);
                var currentAwardFrequency = _nominationService.GetAwardFrequencyById(awardOfCurrentNomination.FrequencyId);
                #region RestrictManagerLogic

                var noOfNominationForManager = Convert.ToInt32(ConfigurationManager.AppSettings["noOfNominationForManager"]);
                var startDate = new DateTime();
                var endDate = new DateTime();
                var countOfNomination = 0;
                _logger.Log("Todays Date: " + customDate);
                if (currentAwardFrequency.Code == FrequencyCode.MON.ToString())
                {
                    var firstDateOfCurrentMonth = new DateTime(customDate.Year, customDate.Month, 1);
                    startDate = firstDateOfCurrentMonth;
                    var noOfDaysInCurrentMonth = DateTime.DaysInMonth(customDate.Year, customDate.Month);
                    endDate = new DateTime(customDate.Year, customDate.Month, noOfDaysInCurrentMonth);
                    countOfNomination = _nominationService.GetNominationCountByManagerIdForSom(model.ManagerId, startDate, endDate, model.AwardId);
                }
                else if (currentAwardFrequency.Code == FrequencyCode.YEAR.ToString())
                {
                    var firstDateOfCurrentYear = new DateTime(customDate.Year, 1, 1);
                    startDate = firstDateOfCurrentYear;
                    countOfNomination = _nominationService.GetNominationCountByManagerIdForPinnacle(model.ManagerId, startDate, model.AwardId);
                }

                if (noOfNominationForManager <= countOfNomination)
                {
                    _logger.Log("Nomination-AddNomination-POST-try-if noOfNominationForManager <= countOfNomination");
                    return Json(new { success = true, nominationExceed = true, message = "Only " + noOfNominationForManager + " nominations are allowed for " + awardOfCurrentNomination.Name + " !" }, JsonRequestBehavior.AllowGet);
                }

                #endregion RestrictManagerLogic

                var nomination = new Nomination
                {
                    AwardId = model.AwardId,
                    ManagerId = model.ManagerId,
                    UserId = model.ResourceId
                };

                switch (model.SelectResourcesBy)
                {
                    case "Project":
                        nomination.ProjectID = model.ProjectID;
                        break;
                    case "Department":
                        nomination.DepartmentId = model.DepartmentId;
                        break;
                    case "Other":
                        nomination.Other = true;
                        nomination.OtherNominationReason = model.OtherNominationReason;
                        break;
                    default:
                        break;
                }

                nomination.NominationDate = customDate;
                nomination.IsSubmitted = submit.Equals("Submit");

                foreach (var criteria in model.Comments)
                {
                    if (criteria.Comment != null || criteria.Rating != 0)
                    {
                        nomination.ManagerComments.Add(
                            new ManagerComment
                            {
                                CriteriaId = criteria.Id,
                                Comment = criteria.Comment != null ? criteria.Comment : "",
                                Rating = criteria.Rating,
                                Weightage = criteria.Weightage,
                                FinalScore = 0,
                                AdminComment = ""
                            }
                        );
                    }
                }
                nomination.Comment = model.MainComment != null ? model.MainComment : "";

                nomination.IsLocked = false;
                var wasSubmitted = _awardService.AddNomination(nomination);
                return Json(new { success = wasSubmitted }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                _logger.Log("Nomination-AddNomination-POST-catch");
                _logger.Log("Nomination-AddNomination-POST-" + ex.Message);
            }
            return Json(new { success = false }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult CriteriasForAward(int awardId)
        {
            _logger.Log("Nomination-CriteriasForAward-POST");
            var criteriaList = _awardService.GetCriteriasForAward(awardId);
            return Json(criteriaList, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult CriteriasForAwardPartialView(int awardId)
        {
            _logger.Log("Nomination-CriteriasForAward-POST");
            var criteriaList = _awardService.GetCriteriasForAward(awardId);
            return PartialView("~/Views/Nomination/Shared/_criteriaForAwards.cshtml", criteriaList);
        }

        [HttpPost]
        [CustomeAuthorize(AllowedRole = "Manager")]
        public ActionResult DiscardNomination(int nominationId)
        {
            _logger.Log("Nomination-DiscardNomination-POST");
            _nominationService.DiscardNomination(nominationId);
            return RedirectToAction("GetNominationList");
        }

        [HttpGet]
        [CustomeAuthorize(AllowedRole = "Manager")]
        public ActionResult EditSavedNomination(int nominationId)
        {
            _logger.Log("Nomination-EditSavedNomination-GET");
            var savedNomination = _nominationService.GetNomination(nominationId);

Encourage/Silicus.EncourageWithAzureAd.Web/Views/Nomination/Shared/_criteriaForAwards.cshtml
@model IEnumerable<Silicus.Encourage.Models.Criteria>

<script src="~/js/jquery.barrating.min.js"></script>

<div class="wizard-box" style="margin-top:10px;" id="criterias">
    <div class="row">
        <div class="col-md-12">
            <div class="table-responsive">
                <table class="table table-hover" id="criteriaTable">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Criteria</th>
                            <th>Rating</th>
                            <th>Weightage</th>
                            <th>Manager Comments</th>
                        </tr>
                    </thead>
                    <tbody>
                        @{ int i = 0;}
                        @foreach (var criteria in Model)
                        {
                            <tr>
                                <td>
                                    @(i + 1)
                                </td>
                                <td class="col-lg-5 col-md-4 col-sm-4 col-xs-4">
                                    <label> @criteria.Title</label>
                                </td>
                                <td class="col-lg-3 col-md-4 col-sm-6 col-xs-4">
                                    <select id="rating-@i" class="example-square" name="Comments[@i].Rating" autocomplete="off" value="" row-id="@i" isRequiredForCriteria>
                                        <option value=""></option>
                                        <option value="1">1</option>
                                        <option value="2">2</option>
                                        <option value="3">3</option>
                                        <option value="4">4</option>
                                        <option value="5">5</option>
                                    </select>
                                </td>
                                <td class="col-lg-1 col-md-1 col-sm-1 col-xs-1">
                                    @Html.DropDownList("Comments[" + @i + "].Weightage",
                                    Enumerable.Range(0, 21).Select(x => x * 5).
                                    Select(j => new SelectListItem
                                    {
                                        Value = j.ToString(),
                                        Text = j.ToString()
                                    }), new
                                    {
                                        @class = "form-control ddlWeightage",
                                        @disabled = "disabled",
                                        @isRequiredForCriteria = "false",
                                        @onchange = "checkIfWeightageExceeds(this," + i + ");",
                                        @row_id = i
                                    })
                                </td>
                                <td class="col-lg-3 col-md-4 col-sm-3 col-xs-3">
                                    <textarea class="form-control" onblur="return hideRemainingCharacterText(@i)"
                                              onkeyup="edValueKeyPress(@i)"
                                              rows=""
                                              name="Comments[@i].Comment"
                                              id="@("comment"+i)"
                                              maxlength="500"
                                              isRequiredForCriteria="false"
                                              row-id=@i
                                              disabled="disabled"></textarea>
                                    <div class="@("textarea"+i)"></div>

                                    <div class="col-md-5 criteriaComment">

                                    </div>
                                </td>
                                <td>
                                    <input type="hidden" name="Comments[@i].Id" value="@criteria.Id">
                                    <span class="hide">@(i++)</span>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        var ratings = $('.example-square');

        $.each(ratings, function (index) {
            var id = "#"+this.id;
            var rating = +this.getAttribute("value");

            $(id).barrating('show', {
                theme: 'bars-square',
                showValues: true,
                showSelectedRating: false,
                onSelect: function(value, text,event) {
                    var element = this.$elem[0];
                    var rowId = +element.getAttribute("row-id");

                    var commentId = "#comment"+rowId;
                    var weightageId = "#Comments_"+rowId+"__Weightage";
                    if (+value != 0) {
                        $(commentId).attr("isRequiredForCriteria", true);
                        $(weightageId).attr("isRequiredForCriteria", true);
                        if ($(commentId).val() == "") {
                            $(commentId).removeAttr("disabled");
                            $(weightageId).removeAttr("disabled");

                            $(commentId).addClass("noCommentError");
                            $(weightageId).addClass("noCommentError");
                        }
                    }else{
                        $(commentId).attr("isRequiredForCriteria", false);
                        $(commentId).removeClass("noCommentError");
                        $(commentId).attr("disabled", "disabled");
                        $(commentId).val("");


                        $(weightageId).attr("isRequiredForCriteria", false);
                        $(weightageId).removeClass("noCommentError");
                        $(weightageId).attr("disabled", "disabled");
                        $(weightageId).val(0);
                    }
                }
            });

            $(id).barrating('set',rating);
        })
    });

    function checkIfWeightageExceeds(dd,rowId){
        if(dd.value > 0){
            $(dd).removeClass("noCommentError");
        }else {
            $(dd).addClass("noCommentError");
        }

        if(checkWeightage() >= 100)
        {
            var currentRowId = 0;
            //currentRowId = this.attributes.getNamedItem("row-id").value;
            var skipDisabling = false;
            var allRequiredFields = $("[isRequiredForCriteria]");
            $.each(allRequiredFields,function(){
                //debugger;
                if (this.classList.contains("example-square")) {
                    var rating = this.value;
                    if (rating > 0) {
                        skipDisabling = true;
                    } else {
                        skipDisabling = false;
                    }
                }

                if(!skipDisabling)
                {
                    $(this).attr("disabled", "disabled");
                }
            });
        }
    }
</script>

Encourage/Silicus.EncourageWithAzureAd.Web/Views/Nomination/Shared/_savedReviewsList.cshtml
@model IEnumerable<Silicus.EncourageWithAzureAd.Web.Models.NominationListViewModel>

@if (Model.Count() > 0)
{
    foreach (var item in Model)
    {
        <div class="el-element-overlay m-b-40">
            <div class="col-lg-2 col-md-3 col-sm-4 col-xs-4">
                <div class="@(item.IsSubmitted == true ? "blue-box" : "white-box")">
                    <div class="el-card-item">
                        <div class="el-card-avatar el-overlay-1">
                            @if (File.Exists(Server.MapPath("~/UserProfilePicture") + "/" + item.EmployeeId + ".jpg"))
                            {
                                <img src="~/UserProfilePicture/@(item.EmployeeId).jpg" />
                            }
                            else
                            {
                                <img src="~/UserProfilePicture/Default.jpg" />
                            }
                            <div class="el-overlay">
                                <ul class="el-info">
                                    <li>

                                        @if (!Convert.ToBoolean(item.IsSubmitted))
                                        {
                                            <a class="btn default btn-outline image-popup-vertical-fit" href="@Url.Action("EditReview", "Nomination", new { nominationId = item.Id })">
                                                <i class="fa fa-pencil-square-o fa-2x" aria-hidden="true"></i>
                                            </a>
                                        }
                                        else
                                        {
                                            <a class="btn default btn-outline image-popup-vertical-fit" href="@Url.Action("ReviewDetails", "Nomination", new { nominationId = item.Id })">

                                                <i class="fa fa-file-text-o fa-2x" aria-hidden="true"></i>
                                            </a>
                                        }
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="el-card-content">
                            <h3 class="box-title">@Html.DisplayFor(modelItem => item.DisplayName)</h3>
                            <small>
                                @Html.DisplayFor(modelItem => item.AwardName)
                                @Html.DisplayFor(modelItem => item.NominationTime)
                            </small><br>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
}
else
{
    <div class="row" id="noHistoricalData">
        <div class="col-sm-12">
            <div class="alert alert-danger">
                <span class="text-danger" style="font-size:20px">No employees found for review under this award category!</span>
            </div>
        </div>
    </div>
}

Encourage/Silicus.EncourageWithAzureAd.Web/Views/Nomination/Shared/_savednominationList.cshtml
@model IEnumerable<Silicus.EncourageWithAzureAd.Web.Models.NominationListViewModel>
@using Silicus.EncourageWithAzureAd.Web.Enums;

@if (Model.Count() > 0)
{
    foreach (var item in Model)
    {
        <div class="el-element-overlay m-b-40">
            <div class="col-lg-2 col-md-3 col-sm-4 col-xs-4">
                <div class="@(item.IsSubmitted == true ? "blue-box" : "white-box")">
                    <div class="el-card-item">
                        <div class="el-card-avatar el-overlay-1">
                            @if (File.Exists(Server.MapPath("~/UserProfilePicture") + "/" + item.EmployeeId + ".jpg"))
                            {
                                <img src="~/UserProfilePicture/@(item.EmployeeId).jpg" />
                            }
                            else
                            {
                                <img src="~/UserProfilePicture/Default.jpg" />
                            }
                            <div class="el-overlay">
                                <ul class="el-info">
                                    <li>
                                        <a class="btn default btn-outline image-popup-vertical-fit" href="@Url.Action("EditSavedNomination", "Nomination", new { nominationId = item.Id })">
                                            @if (item.IsSubmitted == true)
                                            {
                                                <i class="fa fa-file-text-o fa-2x" aria-hidden="true"></i>
                                            }
                                            else
                                            {
                                                <i class="fa fa-pencil-square-o fa-2x" aria-hidden="true"></i>
                                            }
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="el-card-content">
                            <h3>@Html.DisplayFor(modelItem => item.DisplayName)</h3>
                            <small>
                                @Html.DisplayFor(modelItem => item.AwardName)
                                @if (item.AwardFrequencyCode == FrequencyCode.YEAR.ToString())
                                {
                                    var nominationYear = Convert.ToInt32(item.NominationTime.Substring(item.NominationTime.LastIndexOf('-') + 1));
                                    @Html.Label("-" + Convert.ToInt32(nominationYear))

                                }
                                else
                                {
                                    @Html.DisplayFor(modelItem => item.NominationTime)
                                }

                            </small><br>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
}
else
{
    <div class="row" id="noHistoricalData">
        <div class="col-sm-12">
            <div class="alert alert-danger">
                <span class="text-danger" style="font-size:20px">No employees found under this award category!</span>
            </div>
        </div>
    </div>
}