Enboard/HR_Web/Controllers/EducationController.cs
using AutoMapper;
using Data;
using Models;
using PagedList;
using Service;
using Service.Interface;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace HR_Web.Controllers
{
    [Authorize]
    public class EducationController : Controller
    {
        int userId = 0;
        string userName = null;

        //service call
        private IEducationService _IEducationService;
        private IClassService _IClassService;
        private ICollegeService _ICollegeService;
        private IDisciplineService _IDisciplineService;
        private IEducationCategoryService _IEducationCategoryService;
        private ISpecializationService _ISpecializationService;
        private IUniversityService _IUniversityService;
        private IUserService _IUserService;
        private IEducationCategoryUniversityBoardMappingService _IEducationCategoryUniversityBoardMappingService;

        //Data class
        EmployeeEducationDetail _educationDetails;
        Master_Class _class;
        Master_College _college;
        Master_Discipline _discipline;
        Master_EducationCategory _educationCategory;
        Master_Specialization _specialization;
        Master_University _university;
        EducationCategoryUniversityBoardMapping _educationCategoryUniversityBoardMapping;

        public EducationController(IUserService IUserService, IEducationService IEducationService, IClassService IClassService, ICollegeService ICollegeService, IDisciplineService IDisciplineService,
            IEducationCategoryService IEducationCategoryService, ISpecializationService ISpecializationService, IUniversityService IUniversityService, IEducationCategoryUniversityBoardMappingService IEducationCategoryUniversityBoardMappingService)
        {
            this._IUserService = IUserService;
            this._IEducationService = IEducationService;
            _educationDetails = new EmployeeEducationDetail();
            this._IClassService = IClassService;
            _class = new Master_Class();
            this._ICollegeService = ICollegeService;
            _college = new Master_College();
            this._IDisciplineService = IDisciplineService;
            _discipline = new Master_Discipline();
            this._IEducationCategoryService = IEducationCategoryService;
            _educationCategory = new Master_EducationCategory();
            this._ISpecializationService = ISpecializationService;
            _specialization = new Master_Specialization();
            this._IUniversityService = IUniversityService;
            _university = new Master_University();
            this._IEducationCategoryUniversityBoardMappingService = IEducationCategoryUniversityBoardMappingService;
            _educationCategoryUniversityBoardMapping = new EducationCategoryUniversityBoardMapping();

        }
        public EducationController()
        {

        }

        /*New Code Education Details */
        /*Grid Code */


        [HttpGet]
        [Authorize]
        public ActionResult GetEducationalDetailsGrid(int userId)
        {
            //Models.EducationDetails EducationModel = new EducationDetails();
            //EducationModel.EducationalDetailsList = EducationListPagedList(userId);
            //return View("_GetEducationList", EducationModel.EducationalDetailsList);

            ViewBag.Classes = GetClasses();
            ViewBag.Discipline = GetDiscipline(0);
            ViewBag.Colleges = GetColleges();
            ViewBag.EducationCategory = GetEducationCategory();
            ViewBag.Specialization = GetSpecialization();
            ViewBag.University = GetUniversity();
            ViewBag.Months = GetMonths();
            ViewBag.Years = GetYears();

            EducationDetails educationModel = new EducationDetails();

            List<EmployeeEducationDetail> list = _IEducationService.GetEmployeeEducationDetailsByUserID(userId);
            educationModel.educationDetialslist = list
            .Select(x => new EducationDetails()
            {
                EduDetID = x.EduDetID,
                UserId = x.UserID,
                FromDate = x.FromDate,
                EducationCategoryId = x.EducationCategoryID,
                OtherEducationCategory = x.OtherEducationCategory,
                ToDate = x.ToDate,
                BreaksDuringEducation = x.BreaksDuringEducation,
                ClassId = x.ClassID,
                TypeofDegreeDeplomaId = x.DisciplineID,
                OtherDiscipline = x.OtherDiscipline,
                PassingYear = x.PassingYear,
                OtherSpecialization = x.OtherSpecialization,
                InstituteNameId = x.CollegeID,
                OtherCollegeName = x.OtherCollegeName,
                University_BoardNameId = x.UniversityID,
                OtherUniversityName = x.OtherUniversityName,
                Percentage = x.Percentage,
                UniversityList = GetUniversityList(x.EducationCategoryID)

            }).OrderByDescending(x => x.PassingYear).ToList();

            foreach (var item in educationModel.educationDetialslist)
            {
                if (item.EducationCategoryId == 0)
                {
                    item.EducationCategory = item.OtherEducationCategory;
                }
                else
                {
                    item.EducationCategory = (from pair in ViewBag.EducationCategory as SelectList
                                              where pair.Value == item.EducationCategoryId.ToString()
                                              select pair.Text).FirstOrDefault();
                }
            }


            ViewBag.EducationCategoryForUser = GetEducationCategoryByEducationId(userId);
            var userDetails = _IUserService.GetById(userId);
            ViewBag.IsSubmitted = userDetails == null ? false : userDetails.IsSubmitted.HasValue && userDetails.IsSubmitted.Value == true;
            return View("_GetEducationList", educationModel);
        }

        [HttpGet]
        [Authorize]
        public ActionResult AddEditEducationDetails(int EducationId = 0, bool IsReadOnly = false)
        {
            ViewBag.Classes = GetClasses();
            ViewBag.Discipline = GetDiscipline(0);
            ViewBag.Colleges = GetColleges();
            ViewBag.EducationCategory = GetEducationCategory();
            ViewBag.Specialization = GetSpecialization();
            ViewBag.University = GetUniversity();
            ViewBag.Months = GetMonths();
            ViewBag.Years = GetYears();

            ViewBag.IsReadOnly = IsReadOnly;
            ViewBag.IsEditPage = false;
            if (System.Web.HttpContext.Current.Request.IsAuthenticated)
            {
                userId = Convert.ToInt32(System.Web.HttpContext.Current.User.Identity.Name.Split('|')[1]);
                userName = System.Web.HttpContext.Current.User.Identity.Name.Split('|')[0];

                //var res = user.Where(u => u.Password == details.Password && u.Email.ToLower() == details.Email.ToLower()).SingleOrDefault();
                var eduDetails_lst = _IEducationService.GetAll(null, null, "");
                Session["eduDetails_lst"] = eduDetails_lst;

                var obj = eduDetails_lst.Where(u => u.UserID == userId && u.EduDetID == EducationId).FirstOrDefault();
                if (obj != null)
                {
                    _educationDetails = obj;
                }

            }
            Models.EducationDetails model = new EducationDetails();
            if (EducationId != 0)
            {
                Mapper.CreateMap<Data.EmployeeEducationDetail, Models.EducationDetails>();
                model = Mapper.Map<Data.EmployeeEducationDetail, Models.EducationDetails>(_educationDetails);

                //By Sachin Khot
                //model.EducationCategoryId = Convert.ToInt32(model.EducationCategory);
                model.EducationCategoryId = Convert.ToInt32(model.EducationCategoryId);
                //model.InstituteNameId = Convert.ToInt32(model.InstituteName);
                model.InstituteNameId = Convert.ToInt32(model.CollegeID);
                //model.University_BoardNameId = Convert.ToInt32(model.University_BoardName);
                model.University_BoardNameId = Convert.ToInt32(model.UniversityID);
                //model.ClassId = Convert.ToInt32(model.Class);
                model.ClassId = Convert.ToInt32(model.ClassId);

                //ViewBag.Discipline = GetDiscipline(Convert.ToInt32(model.TypeofDegreeDeploma));
                ViewBag.Discipline = GetDiscipline(Convert.ToInt32(model.DisciplineID));

                //model.TypeofDegreeDeplomaId = Convert.ToInt32(model.TypeofDegreeDeploma);
                model.TypeofDegreeDeplomaId = Convert.ToInt32(model.DisciplineID);

                //model.SpecializationId = Convert.ToInt32(model.Specialization);
                model.SpecializationId = Convert.ToInt32(model.SpecializationId);
                ViewBag.IsEditPage = true;
            }
            //Mapper.CreateMap<List<GetEducationList_Result>, List<EducationDetailsHistory>>();            

            //user.EducationalDetailsList = EducationListPagedList(userId);
            return View("EducationalDetails", model);
        }

        [HttpGet]
        [Authorize]
        public ActionResult EducationalDetails(string EducationCategoryId = "1")
        {
            ViewBag.Classes = GetClasses();
            ViewBag.Discipline = GetDiscipline(0);
            ViewBag.Colleges = GetColleges();
            ViewBag.EducationCategory = GetEducationCategory();
            ViewBag.Specialization = GetSpecialization();
            ViewBag.University = GetUniversity();
            ViewBag.Months = GetMonths();
            ViewBag.Years = GetYears();

            if (System.Web.HttpContext.Current.Request.IsAuthenticated)
            {
                userId = Convert.ToInt32(System.Web.HttpContext.Current.User.Identity.Name.Split('|')[1]);

Enboard/HR_Web/Views/Education/_EducationDetailsList.cshtml
@model Models.EducationDetails

 @using (Html.BeginForm("EducationalDetails", "Education", FormMethod.Post, new { id = "ED_FormId" + i.ToString(), @class = "addFormClass" }))
 {
<div class="panel panel-default">
    <div class="panel-heading" role="tab">
        <h4 class="panel-title">
            <a role="button" data-toggle="collapse" data-parent="#proposalAccordian" href="#tr@(i)" aria-expanded="true" class="collapsed">
                @Model.educationDetialslist[i].EducationCategory
            </a>
        </h4>
    </div>
    <div id="tr@(i)" class="panel-collapse collapse" role="tabpanel">
        <div class="panel-body">
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        @Html.LabelFor(m => Model.educationDetialslist[i].EducationCategory, new { @class = "" }) <span class="red">*</span>
                        @Html.DropDownList("EducationCategoryId",
                                                new SelectList(educationCategorylist, "Value", "Text", Model.educationDetialslist[i].EducationCategoryId), "Select Education Category",
                                                      new
                                                      {
                                                          id = "ED_ddlEducationCategory" + i.ToString(),
                                                          @class = "form-control",
                                                          placeholder = "Select Education Category",
                                                          tabindex = 1,
                                                          onchange = "educationCategoryChange(this);"
                                                      })
                        @Html.ValidationMessageFor(m => Model.educationDetialslist[i].EducationCategoryId, "", new { @class = "text-danger" })
                        @Html.TextBox("OtherEducationCategory", Model.educationDetialslist[i].OtherEducationCategory, new { id = "ED_txtOtherEducationCategory" + i, @class = "form-control otherTextBox", placeholder = "Please enter your Education Category", style = "display:none;", tabindex = 1 })
                        @Html.ValidationMessageFor(m => Model.educationDetialslist[i].OtherEducationCategory, "", new { @class = "text-danger", id = "ED_valOtherEducationCategory" + i.ToString() })
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        @Html.LabelFor(m => Model.educationDetialslist[i].TypeofDegreeDeploma, new { @class = "" }) <span class="red">*</span>
                        @Html.DropDownList("TypeofDegreeDeplomaId",
                                                new SelectList(discipline, "Value", "Text", Model.educationDetialslist[i].TypeofDegreeDeplomaId), "Select Discipline",
                                               new
                                               {
                                                   id = "ED_ddlTypeofDegreeDeploma" + i.ToString(),
                                                   @class = "form-control",
                                                   placeholder = "Select Discipline",
                                                   tabindex = 2,
                                                   onchange = "disciplineChange(this);"
                                               })
                        @Html.ValidationMessageFor(m => Model.educationDetialslist[i].TypeofDegreeDeplomaId, "", new { @class = "text-danger" })
                        @Html.TextBox("OtherTypeofDegreeDeploma", Model.educationDetialslist[i].OtherTypeofDegreeDeploma, new { id = "ED_txtOtherTypeofDegreeDeploma" + i, @class = "form-control otherTextBox", placeholder = "Please enter your Discipline", style = "display:none;", tabindex = 2 })
                        @Html.ValidationMessageFor(m => Model.educationDetialslist[i].OtherTypeofDegreeDeploma, "", new { @class = "text-danger", id = "ED_OtherClass" + i.ToString() })
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        @Html.LabelFor(m => Model.educationDetialslist[i].PassingYear, new { @class = "" }) <span class="red">*</span>
                        @Html.DropDownList("PassingYear", new SelectList(Years, "Value", "Text", Model.educationDetialslist[i].PassingYear), "Select Year", new { id = "CD_txtPassingYear" + i.ToString(), @class = "form-control", tabindex = 6 })
                        @Html.ValidationMessageFor(m => Model.educationDetialslist[i].PassingYear, "", new { @class = "text-danger" })
                        <label id="lblPassingYearError" class="text-danger" style="display:none;"> </label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        @Html.LabelFor(m => Model.educationDetialslist[i].Class, new { @class = "" }) <span class="red">*</span>
                        @Html.DropDownList("ClassId", new SelectList(classes, "Value", "Text", Model.educationDetialslist[i].ClassId), "Select class", new { id = "ED_ddlClass" + i.ToString(), @class = "form-control", placeholder = "Select Class", tabindex = 10 })
                        @Html.ValidationMessageFor(m => Model.educationDetialslist[i].ClassId, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        @Html.LabelFor(m => Model.educationDetialslist[i].Specialization, new { @class = "" }) <span class="red">*</span>
                        @Html.TextBox("OtherSpecialization", Model.educationDetialslist[i].OtherSpecialization, new { id = "ED_txtOtherSpecialization" + i.ToString(), @class = "form-control mt-5", placeholder = "Please enter your Specialization", tabindex = 13 })
                        @Html.ValidationMessageFor(m => Model.educationDetialslist[i].OtherSpecialization, "", new { @class = "text-danger", id = "ED_OtherClass" + i.ToString() })
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        @Html.LabelFor(m => Model.educationDetialslist[i].InstituteName, new { @class = "" }) <span class="red">*</span>
                        @Html.DropDownList("InstituteNameId",
                                                new SelectList(college, "Value", "Text", Model.educationDetialslist[i].InstituteNameId), "Select Institute Name",
                                               new
                                               {
                                                   id = "ED_ddlInstituteName" + i.ToString(),
                                                   @class = "form-control",
                                                   placeholder = "Select Institute Name",
                                                   tabindex = 3,
                                                   onchange = "instituteNameChange(this);"
                                               })
                        @Html.ValidationMessageFor(m => Model.educationDetialslist[i].InstituteNameId, "", new { @class = "text-danger" })
                        @Html.TextBox("OtherInstituteName", Model.educationDetialslist[i].OtherInstituteName, new { id = "ED_txtOtherInstituteName" + i, @class = "form-control otherTextBox", placeholder = "Please enter your Institute Name", style = "display:none;", tabindex = 3 })
                        @Html.ValidationMessageFor(m => Model.educationDetialslist[i].OtherInstituteName, "", new { @class = "text-danger", id = "ED_OtherInstituteName" + i.ToString() })
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        @Html.LabelFor(m => Model.educationDetialslist[i].AttendedFrom, new { @class = "" }) <span class="red">*</span>
                        @Html.TextBox("AttendedFrom", Model.educationDetialslist[i].AttendedFrom, new { id = "txtAttendedFrom" + i.ToString(), @class = "form-control", tabindex = 5 })
                        @Html.ValidationMessageFor(m => Model.educationDetialslist[i].AttendedFrom, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        @Html.LabelFor(m => Model.educationDetialslist[i].AttendedTo, new { @class = "" }) <span class="red">*</span>
                        @Html.TextBox("AttendedTo", Model.educationDetialslist[i].AttendedTo, new { id = "txtAttendedTo" + i.ToString(), @class = "form-control", tabindex = 5 })
                        @Html.ValidationMessageFor(m => Model.educationDetialslist[i].AttendedTo, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        @Html.LabelFor(m => Model.educationDetialslist[i].University_BoardName, new { @class = "" }) <span class="red">*</span>
                        @Html.DropDownList("University_BoardNameId",
                                                new SelectList(university, "Value", "Text", Model.educationDetialslist[i].University_BoardNameId), "Select University/Board Name",
                                               new
                                               {
                                                   id = "ED_ddlUniversity_BoardName" + i.ToString(),
                                                   @class = "form-control",
                                                   placeholder = "Select University/Board Name",
                                                   tabindex = 5,
                                                   onchange = "universityBoardNameChange(this);"
                                               })
                        @Html.ValidationMessageFor(m => Model.educationDetialslist[i].University_BoardNameId, "", new { @class = "text-danger" })
                        @Html.TextBox("OtherUniversity_BoardName", Model.educationDetialslist[i].OtherUniversity_BoardName, new { id = "ED_txtOtherUniversity_BoardName" + i, @class = "form-control otherTextBox", placeholder = "Please enter your University / BoardName", style = "display:none;", tabindex = 5 })
                        @Html.ValidationMessageFor(m => Model.educationDetialslist[i].OtherUniversity_BoardName, "", new { @class = "text-danger", id = "ED_OtherUniversity_BoardName" + i.ToString() })
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        @Html.LabelFor(m => Model.educationDetialslist[i].Percentage, new { @class = "" }) <span class="red">*</span>
                        @Html.TextBox("Percentage", Model.educationDetialslist[i].Percentage, new { id = "CD_txtPercentage" + i.ToString(), placeholder = "63.50", @class = "form-control", tabindex = 11, MaxLength = 5 })
                        @Html.ValidationMessageFor(m => Model.educationDetialslist[i].Percentage, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        @Html.LabelFor(m => Model.educationDetialslist[i].BreaksDuringEducation, new { @class = "" }) <span class="red">*</span>
                        @Html.TextBox("BreaksDuringEducation", Model.educationDetialslist[i].BreaksDuringEducation, new { id = "CD_txtBreaks" + i.ToString(), placeholder = "63.50", @class = "form-control", tabindex = 11, MaxLength = 5 })
                        @Html.ValidationMessageFor(m => Model.educationDetialslist[i].BreaksDuringEducation, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            @Html.Hidden("EduDetID", Model.educationDetialslist[i].EduDetID, new { id = "hdEduId" + i.ToString() })
            <div class="row">
                <div class="col-md-12">
                    <a class="btn-delete pull-right" href="#">Delete</a>
                    <a class="btn-reset pull-right" href="#" onclick="editEducationalDetails(this);" data-id='@i' id='btnEducationEdit@(i)'>Edit</a>
                    <button type="submit" name="submit" title="submit" class="btn-reset pull-right" data-id='@i' id='btnEducationEdit@(i)'>Submit</button>
                </div>
            </div>
        </div>
    </div>
 </div>
}