Enboard/HR_Web/Controllers/EmployementController.cs
using AutoMapper;
using Data;
using Models;
using Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace HR_Web.Controllers
{
    [Authorize]
    public class EmployementController : Controller
    {
        int userId = 0;
        string userName = null;

        //service call
        private IEmployementService _IEmployementService;
        private ICityService _ICityService;
        private IStateService _IStateService;
        private ICountryService _ICountryService;
        private IUserService _IUserService;
        private IEmploymentCountService _IEmploymentCountService;

        //Data class
        EmploymentDetail _employement;
        Master_City _city;
        Master_State _state;
        Master_Country _country;


        public EmployementController(IEmployementService IEmployementService, ICityService ICityService, IStateService IStateService, ICountryService ICountryService, IUserService IUserService, IEmploymentCountService IEmploymentCountService)
        {
            this._IEmployementService = IEmployementService;
            _employement = new EmploymentDetail();
            this._ICityService = ICityService;
            _city = new Master_City();
            this._IStateService = IStateService;
            _state = new Master_State();
            this._ICountryService = ICountryService;
            _country = new Master_Country();
            this._IUserService = IUserService;
            this._IEmploymentCountService = IEmploymentCountService;
        }



        public ActionResult Index()
        {
            userId = Convert.ToInt32(System.Web.HttpContext.Current.User.Identity.Name.Split('|')[1]);
            var userDetails = _IUserService.GetById(userId);
            ViewBag.IsSubmitted = userDetails == null ? false : userDetails.IsSubmitted.HasValue && userDetails.IsSubmitted.Value;
            var employmentCount = _IEmploymentCountService.GetEmploymentCountByUserId(userId);

            var employmentList = EmploymentDetailList(userId);
            EmployementModel employementModel = new EmployementModel();
            employementModel.IsCurrentEmployment = false;
            if (TempData["EmployementModel"] != null)
                employementModel = (EmployementModel)TempData["EmployementModel"];
            else if (employmentList.Any(x => x.IsCurrentEmployment == true))
            {
                employementModel.IsCurrentEmployment = false;
            }

            employementModel.NoOfEmployementAdded = employmentList.Count;
            employementModel.CurrencyList = GetCurrencies();
            employementModel.IsFresher = _IEmployementService.IsFresher(userId);
            employementModel.EmploymnetDetailsList = EmploymnetListPagedList(employmentList.OrderByDescending(p => p.ToDate).ToList()).ToList();
            return View(employementModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(EmployementModel employementModel)
        {
            bool status = false;
            string userName = null;

            try
            {
                ModelState.Remove("ReasonForLeave");
                if (ModelState.IsValid)
                {
                    employementModel.UserId = Convert.ToInt32(System.Web.HttpContext.Current.User.Identity.Name.Split('|')[1]);
                    userName = System.Web.HttpContext.Current.User.Identity.Name.Split('|')[0];

                    var employmentList = EmploymentDetailList(Convert.ToInt32(System.Web.HttpContext.Current.User.Identity.Name.Split('|')[1]));

                    var numberOfEmployment = _IEmploymentCountService.GetEmploymentCountByUserId((int)employementModel.UserId);

                    #region commented Validation for Employee count 
                    //==================As Per Comment of EnBoard_ Comments 01-11-2017.docx=====================    
                    /*
                    if (numberOfEmployment != null)
                    {
                        if (numberOfEmployment.NumberOfEmployments == null || employmentList.Count >= numberOfEmployment.NumberOfEmployments)
                        {
                            TempData["EmployementModel"] = employementModel;
                            TempData["Message"] = new ErrorMessageModel()
                            {
                                MessageType = "error",
                                Message = "You cannot add employments more than you specified in Number Of Employments!"
                            };
                            return RedirectToAction("Index");
                        }
                    }
                    else
                    {
                        TempData["EmployementModel"] = employementModel;
                        TempData["Message"] = new ErrorMessageModel()
                        {
                            MessageType = "error",
                            Message = "Please add Number Of Employemnts!"
                        };
                        return RedirectToAction("Index");
                    }
                    */
                    //==================End As Per Comment of EnBoard_ Comments 01-11-2017.docx=====================    
                    #endregion


                    if (employmentList.Count != 0 && employmentList.Any(x => x.IsCurrentEmployment == true) && employementModel.IsCurrentEmployment == true)
                    {
                        TempData["EmployementModel"] = employementModel;
                        TempData["Message"] = new ErrorMessageModel()
                        {
                            MessageType = "error",
                            Message = "Current employment is already added."
                        };
                        return RedirectToAction("Index");

                    }

                    #region Employee Can join same company more than one time 
                    /*
                    if (employmentList.Any(x => x.CompanyName == employementModel.CompanyName))
                    {
                        TempData["EmployementModel"] = employementModel;
                        TempData["Message"] = new ErrorMessageModel()
                        {
                            MessageType = "error",
                            Message = "This employment is already exist."
                        };
                        return RedirectToAction("Index");

                    }
                    */
                    #endregion Employee Can join same company more than one time 
                    if (employementModel.FromDate.HasValue && employementModel.ToDate.HasValue)
                    {
                        if (employementModel.FromDate.Value >= employementModel.ToDate.Value)
                        {
                            TempData["EmployementModel"] = employementModel;
                            TempData["Message"] = new ErrorMessageModel()
                            {
                                MessageType = "error",
                                Message = "Relieving date cannot be less than or equal to date of joining."
                            };
                            return RedirectToAction("Index");
                        }

                    }

                    if (employmentList != null)
                    {
                        var overlappedRecord = employmentList.Where(u => Convert.ToDateTime(u.FromDate) <= Convert.ToDateTime(employementModel.ToDate) && Convert.ToDateTime(employementModel.FromDate) <= Convert.ToDateTime(u.ToDate) && u.IsActive == true).ToList();

                        if (overlappedRecord.Count > 0)
                        {
                            TempData["EmployementModel"] = employementModel;
                            TempData["Message"] = new ErrorMessageModel()
                            {
                                MessageType = "error",
                                Message = "Employment duration should not fall between previous or current employment duration."
                            };
                            return RedirectToAction("Index");
                        }
                    }

                    employementModel.UpdatedBy = userName;
                    employementModel.UpdatedDate = DateTime.UtcNow;

                    Mapper.CreateMap<EmployementModel, Data.EmploymentDetail>();
                    var EmployDetail = Mapper.Map<EmployementModel, Data.EmploymentDetail>(employementModel);


                    if (EmployDetail.CreatedBy == null || EmployDetail.CreatedBy == "")
                        EmployDetail.CreatedBy = userName;
                    if (EmployDetail.CreatedDate == DateTime.MinValue || EmployDetail.CreatedDate == null)
                        EmployDetail.CreatedDate = DateTime.UtcNow;

                    if (EmployDetail.UpdatedBy == null || EmployDetail.UpdatedBy == "")
                        EmployDetail.UpdatedBy = userName;
                    if (EmployDetail.UpdatedDate == DateTime.MinValue || EmployDetail.UpdatedDate == null)
                        EmployDetail.UpdatedDate = DateTime.UtcNow;

                    EmployDetail.EmployementNo = _IEmployementService.GetLatestEmploymentNo(Convert.ToInt32(employementModel.UserId));
                    EmployDetail.IsActive = true;

                    EmployDetail.CompanyCountryID = _ICountryService.GetAll(null, null, "").Where(i => i.Country == "Other").Select(x => x.CountryID).FirstOrDefault();
                    EmployDetail.CompanyStateID = _IStateService.GetAll(null, null, "").Where(i => i.State == "Other").Select(x => x.StateID).FirstOrDefault();
                    EmployDetail.CompanyCityID = _ICityService.GetAll(null, null, "").Where(i => i.City == "Other").Select(x => x.CityID).FirstOrDefault();

Enboard/HR_Web/Views/Employement/EmployementDetails.cshtml
@model Models.EmployementModel
@{
    ViewBag.Title = "EmployementDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
    
    var CityList = (SelectList)ViewBag.Cities;
    var StateList = (SelectList)ViewBag.States;
    var CountryList = (SelectList)ViewBag.Countries;
}

<style>
    .label {
        color: #6D6767;
        font-size: inherit;
    }
    .hline { width:100%; height:1px; background: #fff }
</style>

@Scripts.Render("~/bundles/jquery")
<script src="~/Scripts/EDP_Validations.js"></script>



<div id="accordion" role="tablist" aria-multiselectable="true">
   
    <div class="panel panel-primary">
        <div class="panel-heading clearfix" role="tab" id="headingOne">
            <h4 class="panel-title">
                <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="false" aria-controls="collapseOne" onclick="getdetails('EmployementNo1', collapseOne)">
                    Employement #1
                </a>
            </h4>
        </div>
        <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
            @*@Html.Partial("~/Views/Employement/_EmployementView.cshtml", Model.ElementAt(0))*@

        </div>
    </div>
    <div class="panel panel-primary">
        <div class="panel-heading clearfix" role="tab" id="headingTwo">
            <h4 class="panel-title">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo" onclick="getdetails('EmployementNo2', collapseTwo)">
                    Employement #2
                </a>
            </h4>
        </div>
        <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
            @*@Html.Partial("~/Views/Employement/_EmployementView.cshtml", Model.ElementAt(1))*@
           
        </div>
    </div>
    <div class="panel panel-primary">
        <div class="panel-heading clearfix" role="tab" id="headingThree">
            <h4 class="panel-title">
                <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree" onclick = "getdetails('EmployementNo3', collapseThree)">
                    Employement #3
                </a>
            </h4>
        </div>
        <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
            @*@Html.Partial("~/Views/Employement/_EmployementView.cshtml", Model.ElementAt(2))*@
        </div>
    </div>
    <div class="panel panel-primary">
        <div class="panel-heading clearfix" role="tab" id="headingFour">
            <h4 class="panel-title">
                <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseFour" aria-expanded="false" aria-controls="collapseFour" onclick="getdetails('EmployementNo4', collapseFour)">
                    Employement #4
                </a>
            </h4>
        </div>
        <div id="collapseFour" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFour">
            @*@Html.Partial("~/Views/Employement/_EmployementView.cshtml", Model.ElementAt(3))*@
           
        </div>
    </div>
    <div class="panel panel-primary">
        <div class="panel-heading clearfix" role="tab" id="headingFive">
            <h4 class="panel-title">
                <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseFive" aria-expanded="false" aria-controls="collapseFive" onclick="getdetails('EmployementNo5', collapseFive)">
                    Employement #5
                </a>
            </h4>
        </div>
        <div id="collapseFive" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFive">
            @*@Html.Partial("~/Views/Employement/_EmployementView.cshtml", Model.ElementAt(4))*@
           
        </div>
    </div>
</div>
<script type="text/javascript">

    $(document).ready(function () {
        // getdetails('EmployementNo1', collapseOne)
        ;
        if (@Model.EmploymentDetID == null || @Model.EmploymentDetID==0)
        {
            getdetails('EmployementNo1', collapseOne)
            return;
    }

    else{
            if ('@Model.EmployementNo' != null) {
                if ('@Model.EmployementNo' == 'EmployementNo2') {
                    getdetails('EmployementNo2', collapseTwo)
                }
                else if ('@Model.EmployementNo' == 'EmployementNo3') {
                    getdetails('EmployementNo3', collapseThree)
                }
                else if ('@Model.EmployementNo' == 'EmployementNo4') {
                    getdetails('EmployementNo4', collapseFour)
                }
                else if ('@Model.EmployementNo' == 'EmployementNo5') {
                    getdetails('EmployementNo5', collapseFive)
                }
                else {
                    getdetails('EmployementNo1', collapseOne)
                }
            }
    }
    });




    function getdetails(value, obj)
    {
        Empty();
        ;
        var url = "/Employement/getPartialView/";
        $.ajax({
            url: url,
            data: { EmployementNo: value },
            cache: false,
            type: "GET",
            success: function (data) {;
                Empty();
                $(obj).html(data);
                $(obj).focus();
                $(obj).addClass("in")
            },
            error: function (reponse) {
                alert("error : " + reponse);
            }
        });
    }

    function Empty()
    {
        $('#collapseOne').empty();      
        $('#collapseTwo').empty();
        $('#collapseThree').empty();
        $('#collapseFour').empty();
        $('#collapseFive').empty();

        $('#collapseOne').removeClass("in");
        $('#collapseTwo').removeClass("in");
        $('#collapseThree').removeClass("in");
        $('#collapseFour').removeClass("in");
        $('#collapseFive').removeClass("in");
       
    }


</script>

Enboard/HR_Web/Views/Employement/_ChangeRequestForm.cshtml
@*@model Models.Employment
@using (Ajax.BeginForm("SaveChangeRequestDetails", "Employement", null, new AjaxOptions { HttpMethod = "POST", OnSuccess = "OnSuccessForm" }, new { id = "PD_ChangeRequestFormId" }))
{
    <div class="row">
        <div class="col-md-8">
            <div class="form-group">
                @Html.LabelFor(m => m.NumberOfEmployments) <span class="red">*</span>
                @Html.TextBoxFor(m => m.NumberOfEmployments, new { id = "CRtxtNumberOfEmployments", placeholder = "3", @class = "form-control titleSelect",@maxlength=2, @tabindex = 28 })
                @Html.ValidationMessageFor(model => model.NumberOfEmployments, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
}

<script type="text/javascript">
    $(document).ready(function () {
        numeric($('#CRtxtNumberOfEmployments'));
    //Added below line of code for client side validations
        $.validator.unobtrusive.parse("#PD_ChangeRequestFormId");
    });
</script>*@

Enboard/HR_Web/Views/Employement/_GetEmploymentList.cshtml
@model Models.EmployementModel
@using HR_Web.Helpers;
@{
    ViewBag.Title = "Index";
    Layout = "";    
}
<div class="containerInner">
    <div class="row">
        <div class="col-lg-12">
            @foreach (var item in Model.EmploymnetDetailsList)
            {                
                <div class="panel panel-default" style="margin-bottom:15px" id="@Html.Raw("div"+item.EmploymentId)">
                    <div class="panel-heading text-left" role="tab">
                        <h4 class="panel-title">
                            <a role="button" data-toggle="collapse" data-parent="#proposalAccordian" href="@Html.Raw("#"+item.EmploymentId)" aria-expanded="true" class="collapsed">
                                @item.CompanyName
                                <span class="font-weight-bold">(@Convert.ToDateTime(item.FromDate).ToString("dd MMMM yyyy")</span> -
                                @if (item.IsCurrentEmployment)
                {
                                    <span class="font-weight-bold">Till date)</span>
                                }
                                else
                                {
                                    <span class="font-weight-bold">@Convert.ToDateTime(item.ToDate).ToString("dd MMMM yyyy"))</span>
                                }

                            </a>
                        </h4>
                    </div>
                    @using (Html.BeginForm("EditSave", "Employement", FormMethod.Post, new { id = @Html.Raw("frmEdit" + item.EmploymentId), @class = "employment-details" }))
                    {
                        <div id="@Html.Raw(@item.EmploymentId)" class="panel-collapse collapse" role="tabpanel">
                            <div class="panel-body">
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label>Company Name</label><span class="red">*</span>
                                            @Html.TextBox("CompanyName", @item.CompanyName,
                        new
                        {
                            id = @Html.Raw("CompanyName" + @item.EmploymentId),
                            @readonly = "readonly",
                            @class = "form-control",
                            @tabindex = (@item.EmploymentId + 1).ToString() + 13,
                            @maxlength = "50"

                        })
                                        </div>
                                    </div>
                                    <div class="col-md-8">
                                        <div class="form-group">
                                            <label for="company">Company Address</label><span class="red">*</span>
                                            @Html.TextBox("CompanyAddress", @item.CompanyAddress,
                        new
                        {
                            id = @Html.Raw("CompanyAddress" + @item.EmploymentId),
                            @readonly = "readonly",
                            @class = "form-control",
                            @tabindex = (@item.EmploymentId + 1).ToString() + 14,
                            @maxlength = "50"
                        })
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label>Current Salary per Annum </label><span class="red">*</span> <em>
                                                <i class="infoIcon fa fa-info-circle"
                                                   aria-hidden="true" data-toggle="tooltip" title="Enter 500,000 for Rs. 5 Lacs per annum"></i>
                                            </em>
                                            @Html.TextBox("CTC", @item.CTC,
                        new
                        {
                            id = @Html.Raw("CTC" + @item.EmploymentId),
                            @readonly = "readonly",
                            @class = "form-control",
                            @tabindex = (@item.EmploymentId + 1).ToString() + 15,
                            @maxlength = "50"
                        })
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label>Currency</label><span class="red">*</span>
                                            @CustomHtmlHelper.DropDownListFor((int)item.CurrencyID,
                                                   Model.CurrencyList, 
                                                   "form-control")
                                        </div>
                                    </div>                                 
                                </div>
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label>Date of Joining</label><span class="red">*</span>
                                            <div class="input-group">
                                                @Html.TextBox("FromDate", @item.FromDate, String.Format("{0:dd/mm/yyyy}", (Model == null ? "" : Convert.ToString(Model.FromDate))),
                                new
                                {
                                    id = @Html.Raw("FromDate" + @item.EmploymentId),
                                    @class = "form-control",
                                    @readonly = "readonly",
                                    tabindex = (@item.EmploymentId + 1).ToString() + 18
                                })
                                                <label class="input-group-addon btn" for="@(Html.Raw("FromDate" + @item.EmploymentId))">
                                                    <span class="fa fa-calendar"></span>
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label>
                                                Date of @if (Model.IsCurrentEmployment == true)
                                                {<span>Tentative</span>} Relieving
                                            </label><span class="red">*</span>
                                            <div class="input-group">
                                                @Html.TextBox("ToDate", @item.ToDate, String.Format("{0:dd/mm/yyyy}", (Model == null ? "" : Convert.ToString(Model.ToDate))),
                                new
                                {
                                    id = @Html.Raw("ToDate" + @item.EmploymentId),
                                    @class = "form-control",
                                    @readonly = "readonly",
                                    tabindex = (@item.EmploymentId + 1).ToString() + 19
                                })
                                                <label class="input-group-addon btn" for="@(Html.Raw("ToDate" + @item.EmploymentId))">
                                                    <span class="fa fa-calendar"></span>
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4">

                                        <div class="switchBox">
                                            <label class="switch">
                                                <input type="checkbox" id="@Html.Raw("chk" + @item.EmploymentId)" checked="@item.IsCurrentEmployment" disabled="disabled" name="chkBox">
                                                <span class="slider round"></span>
                                            </label>
                                            @Html.HiddenFor(x => x.IsCurrentEmployment, new { @class = "IsCurrentEmployment" + item.EmploymentId })
                                            <span class="switchBoxTitle pull-left">Recent Tenure</span>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-8">
                                        <div class="form-group">
                                            <label>
                                                Designation @if (Model.IsCurrentEmployment == false)
                                                {<span> (On Leaving)</span>}
                                            </label><span class="red">*</span>
                                            @Html.TextBox("Designation", @item.Designation,
                        new
                        {
                            id = @Html.Raw("Designation" + @item.EmploymentId),
                            @readonly = "readonly",
                            @class = "form-control",
                            @tabindex = (@item.EmploymentId + 1).ToString() + 17,
                            @maxlength = "50"
                        })
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    @if (item.IsCurrentEmployment == false)
                    {
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <label>Reason for Leaving</label><span class="red">*</span>

                                                @Html.TextAreaFor(m => item.ReasonForLeave, 10, 30, new
                                               {
                                                   @readonly = "readonly",
                                                   @class = "form-control",
                                                   tabindex = (@item.EmploymentId + 1).ToString() + 25,
                                                   MaxLength = 350
                                               })

                                            </div>
                                        </div>
                                    }
                                </div>
                            </div>
                        </div>
                    }
                </div>
            }
        </div>
    </div>
</div>

Enboard/HR_Web/Views/Employement/_NumberOfEmployments.cshtml
@*@model Models.Employment

@using (Html.BeginForm("AddNumberOfEmployments", "Employement", FormMethod.Post, new { id = "frmNumberOfEmployments" }))
{

    <div class="form-group">
        @Html.LabelFor(m => m.NumberOfEmployments)

        <div class="form-inline">
            @Html.TextBoxFor(m => m.NumberOfEmployments, new { id = "txtNumberOfEmployments", placeholder = "Number of Employments, Including Current", @class = "form-control alphanumeric", maxlength = "2", tabindex = 1, @style = "min-width:293px !important" })
            <label class="glyphicon glyphicon-info-sign" style="width:25px;" data-toggle="tooltip" data-placement="right" title="If you are a fresher then put value 0, otherwise put number of previous employments including current employment and count should not exceed 20."></label>
            @Html.ValidationMessageFor(model => model.NumberOfEmployments, "", new { @class = "text-danger", id = "valNumberOfEmployments" })
        </div>
        <div class="row btnRow">
            <div class="row">
                <div class="col-md-12">
                    <span class="pull-right userNote"> <i class="fa fa-certificate"></i> Request to <a href="#" onclick="OpenChangeRequestForm()" tabindex="12">Edit</a>  information! </span>
                </div>
            </div>
        </div>
    </div>

}*@



@*<script type="text/javascript">
    $(document).ready(function () {
        $("#txtNumberOfEmployments").prop("disabled", true);
      
    });

    //Function on success of change request form
    function OnSuccessForm(data) {
        if (data.result == true) {
            $('#changeRequestModal').modal('hide');
            toastr.success(data.Message);
        }
        else {
            toastr.error(data.Message);
        }
    }

    //Function on success of change request form
    function OnFailureForm(data) {

        $('#changeRequestModal').modal('hide');

        toastr.error("Error occurred  while saving your request.");
    }

    function CheckNumberOfEmployments() {
        var caption = $("#addNumberOfEmployments").text();
        if (caption == "Edit") {
            event.preventDefault();
            $("#txtNumberOfEmployments").prop("disabled", false);
            $("#addNumberOfEmployments").text("Add");
            return false;
        }
        else {
            $("#frmNumberOfEmployments").submit();
        }
    }

    $("#editNumberOfEmploymentsLink").click(function () {
        $("#addNumberOfEmployments").show();
        $("#txtNumberOfEmployments").prop("disabled", false);
        $("#addNumberOfEmployments").text("Update");
        $("#editNumberOfEmploymentsLink").hide();
        $("#cancelEditNumberOfEmploymentsLink").removeClass("hide");
        $("#cancelEditNumberOfEmploymentsLink").show();
    });

    $("#cancelEditNumberOfEmploymentsLink").click(function () {
        $("#editNumberOfEmploymentsLink").show();
        $("#addNumberOfEmployments").hide();
        $("#cancelEditNumberOfEmploymentsLink").hide();
        $("#txtNumberOfEmployments").prop("disabled", true);
        $("#txtNumberOfEmployments").val(@ViewBag.NumberOfEmployments);
    });

</script>*@